Document: smplayer-themes
Title: Debian smplayer-themes Manual
Author: <insert document author here>
Abstract: This manual describes what smplayer-themes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/smplayer-themes/smplayer-themes.sgml.gz

Format: postscript
Files: /usr/share/doc/smplayer-themes/smplayer-themes.ps.gz

Format: text
Files: /usr/share/doc/smplayer-themes/smplayer-themes.text.gz

Format: HTML
Index: /usr/share/doc/smplayer-themes/html/index.html
Files: /usr/share/doc/smplayer-themes/html/*.html

  
